# Generated by Django 4.0.2 on 2022-05-05 23:12

from django.db import migrations, models
import django.db.models.deletion
import sqlparse.utils


class Migration(migrations.Migration):

    replaces = [('db', '0001_initial'), ('db', '0002_message_delete_book'), ('db', '0003_alter_message_options_alter_message_table'), ('db', '0004_alter_message_options')]

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.IntegerField(db_column='Customer_id', primary_key=True, serialize=False)),
                ('customer_name', models.CharField(blank=True, db_column='CustomerName', max_length=50)),
                ('domain_name', models.CharField(blank=True, db_column='DomainName', max_length=50)),
                ('process_active', models.IntegerField(blank=True, db_column='ProcessActive', null=True)),
                ('sql_connect_string', models.CharField(blank=True, db_column='SQLConnectString', max_length=200)),
            ],
            options={
                'db_table': 'Customer',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='RoleAttribute',
            fields=[
                ('role_attribute_id', models.AutoField(db_column='RoleAttributeID', primary_key=True, serialize=False)),
                ('role_id', models.IntegerField(blank=True, db_column='RoleID', null=True)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('name_value', models.BooleanField(blank=True, db_column='nameValue')),
            ],
            options={
                'db_table': 'RoleAttribute',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roles',
            fields=[
                ('role_id', models.AutoField(db_column='RoleID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, db_column='RoleName', max_length=50)),
                ('description', models.CharField(blank=True, db_column='RoleDescription', max_length=500)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', default=sqlparse.utils.offset, null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', default=sqlparse.utils.offset, null=True)),
                ('data_access', models.BooleanField(blank=True, db_column='DataAccess')),
                ('menu_access', models.BooleanField(blank=True, db_column='MenuAccess')),
                ('dashboard_access', models.BooleanField(blank=True, db_column='DashboardAccess')),
                ('report_access', models.BooleanField(blank=True, db_column='ReportAccess')),
                ('cases', models.BooleanField(blank=True, db_column='Cases')),
            ],
            options={
                'db_table': 'Roles',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(db_column='UserID', primary_key=True, serialize=False)),
                ('user_name', models.CharField(blank=True, db_column='UserName', max_length=50, unique=True)),
                ('name', models.CharField(db_column='Name', default='', max_length=50)),
                ('first_name', models.CharField(blank=True, db_column='FirstName', max_length=50)),
                ('last_name', models.CharField(blank=True, db_column='LastName', max_length=50)),
                ('email', models.CharField(db_column='Email', max_length=100)),
                ('address1', models.CharField(blank=True, max_length=50)),
                ('address2', models.CharField(blank=True, max_length=50)),
                ('city', models.CharField(blank=True, max_length=50)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('zip', models.CharField(blank=True, max_length=16)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=50)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('primary_contact', models.IntegerField(blank=True, db_column='primaryContact', null=True)),
                ('admin', models.IntegerField(blank=True, null=True)),
                ('job_title', models.CharField(blank=True, db_column='JobTitle', max_length=100)),
                ('linked_in', models.CharField(blank=True, db_column='LinkedIn', max_length=200)),
                ('twitter', models.CharField(blank=True, db_column='Twitter', max_length=200)),
                ('face_book', models.CharField(blank=True, db_column='FaceBook', max_length=100)),
                ('picture', models.BinaryField(blank=True, db_column='Picture', null=True)),
                ('bio', models.TextField(blank=True, db_column='Bio')),
                ('salutation', models.CharField(blank=True, db_column='Salutation', max_length=50)),
                ('letter_closing', models.CharField(blank=True, db_column='LetterClosing', max_length=50)),
                ('crypt_password', models.BinaryField(blank=True, db_column='CryptPassword', null=True)),
                ('hashed_key', models.BinaryField(blank=True, db_column='HashedKey', null=True)),
                ('password_size', models.IntegerField(blank=True, db_column='PasswordSize', null=True)),
                ('profile_picture', models.URLField(blank=True, db_column='ProfilePicture', default='', null=True)),
                ('cookie_consent', models.BooleanField(db_column='CookieConsent', default=False)),
                ('cookie_consent_date', models.DateTimeField(blank=True, db_column='CookieConsentDate', null=True)),
            ],
            options={
                'db_table': 'Users',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('user_roles_id', models.AutoField(db_column='UserRolesID', primary_key=True, serialize=False)),
                ('role', models.ForeignKey(blank=True, db_column='RoleID', null=True, on_delete=django.db.models.deletion.CASCADE, to='db.roles')),
                ('user', models.ForeignKey(blank=True, db_column='UserID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='db.user')),
            ],
            options={
                'db_table': 'UserRoles',
                'ordering': ['pk'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UserAttribute',
            fields=[
                ('user_attribute_id', models.AutoField(db_column='UserAttributeID', primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=50)),
                ('value', models.TextField(blank=True, db_column='NameValue')),
                ('user', models.ForeignKey(db_column='UserID', on_delete=django.db.models.deletion.DO_NOTHING, related_name='attributes', to='db.user')),
            ],
            options={
                'db_table': 'UserAttribute',
                'ordering': ['pk'],
                'abstract': False,
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='roles',
            name='created_by',
            field=models.ForeignKey(blank=True, db_column='CreatedByID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles_created', to='db.user'),
        ),
        migrations.AddField(
            model_name='roles',
            name='updated_by',
            field=models.ForeignKey(blank=True, db_column='UpdatedByID', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='roles_updated', to='db.user'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('message_id', models.AutoField(db_column='MessageID', primary_key=True, serialize=False)),
                ('message_text', models.CharField(blank=True, db_column='MessageText', max_length=1000)),
                ('created_by_id', models.IntegerField(blank=True, db_column='CreatedByID', null=True)),
                ('created_date', models.DateTimeField(blank=True, db_column='CreatedDate', null=True)),
                ('updated_id', models.IntegerField(blank=True, db_column='UpdatedID', null=True)),
                ('updated_date', models.DateTimeField(blank=True, db_column='UpdatedDate', null=True)),
                ('recipient', models.ForeignKey(db_column='Recipient', on_delete=django.db.models.deletion.PROTECT, related_name='recipient_messages', to='db.user')),
                ('sender', models.ForeignKey(db_column='Sender', on_delete=django.db.models.deletion.PROTECT, related_name='my_messages', to='db.user')),
            ],
            options={
                'db_table': 'Messages',
                'ordering': ['pk'],
                'abstract': False,
                'managed': True,
            },
        ),
    ]
