# Generated by Django 4.0.2 on 2022-05-05 23:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0002_message_delete_book'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'managed': True, 'ordering': ['pk']},
        ),
        migrations.AlterModelTable(
            name='message',
            table='Message',
        ),
    ]
